#!/usr/bin/env node
/**
 * WhatsApp MCP Server — Personal AI Employee
 *
 * Implements MCP over stdio using Meta WhatsApp Cloud API.
 * ALWAYS requires human approval before sending messages.
 *
 * Tools:
 *   - send_whatsapp_message    Send a text message (HITL required)
 *   - send_whatsapp_template   Send a pre-approved template message
 *   - check_whatsapp_queue     Check Inbox/whatsapp_incoming.json for new messages
 *   - queue_whatsapp_reply     Queue a reply for human approval (writes to Pending_Approval/)
 *
 * Setup:
 *   Set in .env:
 *     WHATSAPP_ACCESS_TOKEN
 *     WHATSAPP_PHONE_NUMBER_ID
 *     WHATSAPP_WEBHOOK_VERIFY_TOKEN
 */

import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";
import axios from "axios";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const VAULT_PATH = path.resolve(__dirname, "..", "..");
const PENDING_APPROVAL = path.join(VAULT_PATH, "Pending_Approval");
const WA_QUEUE = path.join(VAULT_PATH, "Inbox", "whatsapp_incoming.json");

function getWhatsAppConfig() {
  const token = process.env.WHATSAPP_ACCESS_TOKEN;
  const phoneId = process.env.WHATSAPP_PHONE_NUMBER_ID;
  if (!token || !phoneId) {
    throw new Error(
      "WHATSAPP_ACCESS_TOKEN and WHATSAPP_PHONE_NUMBER_ID must be set in .env"
    );
  }
  return {
    token,
    phoneId,
    url: `https://graph.facebook.com/v18.0/${phoneId}/messages`,
    headers: {
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
    },
  };
}

function writeApprovalFile(phone, message, draftId) {
  fs.mkdirSync(PENDING_APPROVAL, { recursive: true });
  const ts = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
  const filename = `WHATSAPP_REPLY_${ts}.md`;
  const filepath = path.join(PENDING_APPROVAL, filename);

  const content = `---
type: whatsapp_reply
action: send_whatsapp_message
to: "${phone}"
draft_id: "${draftId}"
created: ${new Date().toISOString()}
status: pending_approval
approved: false
---

## WhatsApp Reply Pending Approval

**To:** ${phone}

**Message:**

${message}

---

## To Approve

Set \`approved: true\` in the frontmatter, OR move this file to \`Approved/\` folder.

The system will send the message automatically after approval.

---
*Generated by WhatsApp MCP Server*
`;
  fs.writeFileSync(filepath, content, "utf8");
  return filename;
}

// ── MCP Server ────────────────────────────────────────────────────────────────

const server = new Server(
  { name: "whatsapp-mcp", version: "2.0.0" },
  { capabilities: { tools: {} } }
);

server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: [
    {
      name: "send_whatsapp_message",
      description:
        "Send a WhatsApp message via Meta Cloud API. SECURITY: This creates an approval request in Pending_Approval/ — human must approve before message is sent.",
      inputSchema: {
        type: "object",
        properties: {
          phone_number: {
            type: "string",
            description:
              "Recipient phone number in E.164 format (e.g. +15551234567)",
          },
          message: {
            type: "string",
            description: "Message text to send",
          },
          force_send: {
            type: "boolean",
            description:
              "Set to true ONLY if human has already approved (default: false — creates approval request)",
            default: false,
          },
        },
        required: ["phone_number", "message"],
      },
    },
    {
      name: "send_whatsapp_template",
      description:
        "Send a pre-approved WhatsApp Business template message (no additional approval needed).",
      inputSchema: {
        type: "object",
        properties: {
          phone_number: { type: "string" },
          template_name: {
            type: "string",
            description: "Name of the pre-approved template",
          },
          language_code: { type: "string", default: "en" },
          components: {
            type: "array",
            description: "Template variable components",
          },
        },
        required: ["phone_number", "template_name"],
      },
    },
    {
      name: "check_whatsapp_queue",
      description:
        "Check for pending WhatsApp messages in the incoming queue (Inbox/whatsapp_incoming.json).",
      inputSchema: { type: "object", properties: {} },
    },
    {
      name: "queue_whatsapp_reply",
      description:
        "Queue a WhatsApp reply for human approval. Writes to Pending_Approval/ folder.",
      inputSchema: {
        type: "object",
        properties: {
          phone_number: { type: "string" },
          message: { type: "string" },
          draft_id: { type: "string", description: "Reference ID for this draft" },
        },
        required: ["phone_number", "message"],
      },
    },
  ],
}));

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;

  try {
    if (name === "queue_whatsapp_reply") {
      const draftId = args.draft_id || `wa_draft_${Date.now()}`;
      const filename = writeApprovalFile(args.phone_number, args.message, draftId);
      return {
        content: [
          {
            type: "text",
            text: JSON.stringify({
              success: true,
              approval_file: filename,
              message: `Reply queued for approval. Review: Pending_Approval/${filename}`,
            }),
          },
        ],
      };
    }

    if (name === "send_whatsapp_message") {
      // Default: create approval request instead of sending
      if (!args.force_send) {
        const draftId = `wa_${Date.now()}`;
        const filename = writeApprovalFile(args.phone_number, args.message, draftId);
        return {
          content: [
            {
              type: "text",
              text: JSON.stringify({
                approval_required: true,
                approval_file: filename,
                message:
                  "Message NOT sent. Approval request created in Pending_Approval/. Set approved: true to send.",
              }),
            },
          ],
        };
      }

      // force_send=true: human has approved, actually send
      const cfg = getWhatsAppConfig();
      const payload = {
        messaging_product: "whatsapp",
        recipient_type: "individual",
        to: args.phone_number,
        type: "text",
        text: { preview_url: false, body: args.message },
      };

      const res = await axios.post(cfg.url, payload, { headers: cfg.headers });
      return {
        content: [
          {
            type: "text",
            text: JSON.stringify({
              success: true,
              message_id: res.data.messages?.[0]?.id,
              message: `WhatsApp message sent to ${args.phone_number}`,
            }),
          },
        ],
      };
    }

    if (name === "send_whatsapp_template") {
      const cfg = getWhatsAppConfig();
      const payload = {
        messaging_product: "whatsapp",
        to: args.phone_number,
        type: "template",
        template: {
          name: args.template_name,
          language: { code: args.language_code || "en" },
          components: args.components || [],
        },
      };

      const res = await axios.post(cfg.url, payload, { headers: cfg.headers });
      return {
        content: [
          {
            type: "text",
            text: JSON.stringify({
              success: true,
              message_id: res.data.messages?.[0]?.id,
              message: `Template '${args.template_name}' sent to ${args.phone_number}`,
            }),
          },
        ],
      };
    }

    if (name === "check_whatsapp_queue") {
      if (!fs.existsSync(WA_QUEUE)) {
        return {
          content: [{ type: "text", text: JSON.stringify({ pending: [], count: 0 }) }],
        };
      }
      const data = JSON.parse(fs.readFileSync(WA_QUEUE, "utf8"));
      const pending = Array.isArray(data) ? data : data.pending || [];
      return {
        content: [
          {
            type: "text",
            text: JSON.stringify({ pending, count: pending.length }),
          },
        ],
      };
    }

    throw new Error(`Unknown tool: ${name}`);
  } catch (error) {
    const msg = error.response?.data
      ? JSON.stringify(error.response.data)
      : error.message;
    return {
      content: [{ type: "text", text: JSON.stringify({ error: msg }) }],
      isError: true,
    };
  }
});

const transport = new StdioServerTransport();
await server.connect(transport);
