#!/usr/bin/env python3
"""
Approval CLI Tool for Human Workflow

This script provides a command-line interface for humans to review and approve/reject
requests generated by the AI employee. It supports listing pending approvals,
viewing details, and approving or rejecting requests.
"""

import os
import sys
import argparse
import yaml
from pathlib import Path
from datetime import datetime
import json
from typing import Optional


# Configuration
VAULT_PATH = r"C:\Users\laptop world\Desktop\Hack00"
PENDING_DIR = os.path.join(VAULT_PATH, "04_Approval_Workflows", "Pending")
APPROVED_DIR = os.path.join(VAULT_PATH, "04_Approval_Workflows", "Approved")
REJECTED_DIR = os.path.join(VAULT_PATH, "04_Approval_Workflows", "Rejected")


def get_colorama():
    """Try to import colorama for colorful output, return None if not available."""
    try:
        import colorama
        colorama.init()
        return colorama
    except ImportError:
        return None


def format_timestamp(timestamp_str):
    """Format timestamp string to human-readable form."""
    try:
        dt = datetime.fromisoformat(timestamp_str.replace('Z', '+00:00'))
        now = datetime.now(dt.tzinfo)
        diff = now - dt
        
        if diff.days > 0:
            return f"{diff.days} days ago"
        elif diff.seconds >= 3600:
            hours = diff.seconds // 3600
            return f"{hours} hours ago"
        elif diff.seconds >= 60:
            minutes = diff.seconds // 60
            return f"{minutes} min ago"
        else:
            return f"{diff.seconds} sec ago"
    except:
        return timestamp_str


def list_approvals():
    """List all pending approval requests."""
    colorama = get_colorama()
    
    # Colors
    GREEN = colorama.Fore.GREEN if colorama else ""
    YELLOW = colorama.Fore.YELLOW if colorama else ""
    RED = colorama.Fore.RED if colorama else ""
    BLUE = colorama.Fore.BLUE if colorama else ""
    RESET = colorama.Style.RESET_ALL if colorama else ""
    
    pending_dir = Path(PENDING_DIR)
    if not pending_dir.exists():
        print(f"{RED}Error: Pending directory does not exist: {PENDING_DIR}{RESET}")
        return
    
    files = list(pending_dir.glob("*.md"))
    if not files:
        print(f"{YELLOW}No pending approvals found.{RESET}")
        return
    
    print(f"{GREEN}ID{' ' * 2}| Type{' ' * 7}| Details{' ' * 18}| Created{RESET}")
    print("-" * 60)
    
    for file_path in files:
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                content = f.read()
            
            # Extract frontmatter
            if content.startswith('---'):
                end_frontmatter = content.find('---', 3)
                if end_frontmatter != -1:
                    frontmatter = content[3:end_frontmatter].strip()
                    try:
                        metadata = yaml.safe_load(frontmatter)
                        approval_id = metadata.get('approval_id', 'N/A')
                        approval_type = metadata.get('action', 'unknown')
                        
                        # Extract details based on type
                        details = "N/A"
                        if approval_type == 'email_draft':
                            # Look for email details in the content
                            if 'To:' in content:
                                start = content.find('To:') + 3
                                end = content.find('\n', start)
                                to_addr = content[start:end].strip() if end != -1 else content[start:].strip()
                                details = f"To: {to_addr}"
                            elif 'to:' in content:
                                start = content.find('to:') + 3
                                end = content.find('\n', start)
                                to_addr = content[start:end].strip() if end != -1 else content[start:].strip()
                                details = f"To: {to_addr}"
                        elif approval_type == 'payment':
                            # Look for payment details in the content
                            if 'Amount:' in content:
                                start = content.find('Amount:') + 7
                                end = content.find('\n', start)
                                amount = content[start:end].strip() if end != -1 else content[start:].strip()
                                details = f"Amount: {amount}"
                            elif 'amount:' in content:
                                start = content.find('amount:') + 7
                                end = content.find('\n', start)
                                amount = content[start:end].strip() if end != -1 else content[start:].strip()
                                details = f"Amount: {amount}"
                        else:
                            # For other types, just show the type
                            details = f"{approval_type.replace('_', ' ').title()} request"
                        
                        created = metadata.get('created', '')
                        if created:
                            created = format_timestamp(created)
                        
                        # Format the row
                        id_col = f"{approval_id[:3]:<3}" if len(approval_id) >= 3 else f"{approval_id:<3}"
                        type_col = f"{approval_type[:9]:<9}" if len(approval_type) >= 9 else f"{approval_type:<9}"
                        details_col = f"{details[:23]:<23}" if len(details) >= 23 else f"{details:<23}"
                        
                        print(f"{BLUE}{id_col}{RESET} | {YELLOW}{type_col}{RESET} | {details_col} | {created}")
                    except yaml.YAMLError:
                        print(f"{RED}Error parsing frontmatter in {file_path.name}{RESET}")
                else:
                    print(f"{RED}Invalid frontmatter format in {file_path.name}{RESET}")
            else:
                print(f"{RED}No frontmatter found in {file_path.name}{RESET}")
                
        except Exception as e:
            print(f"{RED}Error reading {file_path.name}: {str(e)}{RESET}")


def show_approval(filename: str):
    """Show the full content of an approval request."""
    colorama = get_colorama()
    
    # Colors
    CYAN = colorama.Fore.CYAN if colorama else ""
    MAGENTA = colorama.Fore.MAGENTA if colorama else ""
    GREEN = colorama.Fore.GREEN if colorama else ""
    RED = colorama.Fore.RED if colorama else ""
    RESET = colorama.Style.RESET_ALL if colorama else ""
    
    file_path = Path(PENDING_DIR) / filename
    
    if not file_path.exists():
        print(f"{RED}Error: File not found: {file_path}{RESET}")
        return
    
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        print(f"{CYAN}=== APPROVAL REQUEST DETAILS ==={RESET}\n")
        print(content)
        print(f"\n{MAGENTA}=== END OF CONTENT ==={RESET}")
        
    except Exception as e:
        print(f"{RED}Error reading file {filename}: {str(e)}{RESET}")


def approve_file(filename: str):
    """Approve an approval request by adding metadata and moving to Approved folder."""
    colorama = get_colorama()
    
    # Colors
    GREEN = colorama.Fore.GREEN if colorama else ""
    RED = colorama.Fore.RED if colorama else ""
    RESET = colorama.Style.RESET_ALL if colorama else ""
    
    file_path = Path(PENDING_DIR) / filename
    
    if not file_path.exists():
        print(f"{RED}Error: File not found: {file_path}{RESET}")
        return
    
    try:
        # Read the current content
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        # Parse frontmatter
        if content.startswith('---'):
            end_frontmatter = content.find('---', 3)
            if end_frontmatter != -1:
                frontmatter = content[3:end_frontmatter].strip()
                rest_of_content = content[end_frontmatter + 3:]
                
                # Load existing metadata
                metadata = yaml.safe_load(frontmatter)
                
                # Add approval metadata
                metadata['approved_by'] = 'human'
                metadata['approved_at'] = datetime.now().isoformat()
                metadata['status'] = 'approved'
                
                # Reconstruct the content with updated frontmatter
                updated_frontmatter = yaml.dump(metadata, default_flow_style=False)
                new_content = f"---\n{updated_frontmatter}---\n{rest_of_content.lstrip()}"
                
                # Write back to file temporarily
                with open(file_path, 'w', encoding='utf-8') as f:
                    f.write(new_content)
            else:
                print(f"{RED}Invalid frontmatter format in {filename}{RESET}")
                return
        else:
            print(f"{RED}No frontmatter found in {filename}{RESET}")
            return
        
        # Move file to Approved directory
        approved_dir = Path(APPROVED_DIR)
        approved_dir.mkdir(parents=True, exist_ok=True)
        
        new_file_path = approved_dir / filename
        file_path.rename(new_file_path)
        
        print(f"{GREEN}✅ Approved! File moved to Approved folder{RESET}")
        
    except Exception as e:
        print(f"{RED}Error approving file {filename}: {str(e)}{RESET}")


def reject_file(filename: str):
    """Reject an approval request by adding metadata and moving to Rejected folder."""
    colorama = get_colorama()
    
    # Colors
    RED = colorama.Fore.RED if colorama else ""
    YELLOW = colorama.Fore.YELLOW if colorama else ""
    RESET = colorama.Style.RESET_ALL if colorama else ""
    
    file_path = Path(PENDING_DIR) / filename
    
    if not file_path.exists():
        print(f"{RED}Error: File not found: {file_path}{RESET}")
        return
    
    try:
        # Get rejection reason from user
        reason = input(f"{YELLOW}Enter rejection reason (optional): {RESET}").strip()
        if not reason:
            reason = "No reason provided"
        
        # Read the current content
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        # Parse frontmatter
        if content.startswith('---'):
            end_frontmatter = content.find('---', 3)
            if end_frontmatter != -1:
                frontmatter = content[3:end_frontmatter].strip()
                rest_of_content = content[end_frontmatter + 3:]
                
                # Load existing metadata
                metadata = yaml.safe_load(frontmatter)
                
                # Add rejection metadata
                metadata['rejected_by'] = 'human'
                metadata['rejected_at'] = datetime.now().isoformat()
                metadata['rejection_reason'] = reason
                metadata['status'] = 'rejected'
                
                # Reconstruct the content with updated frontmatter
                updated_frontmatter = yaml.dump(metadata, default_flow_style=False)
                new_content = f"---\n{updated_frontmatter}---\n{rest_of_content.lstrip()}"
                
                # Write back to file temporarily
                with open(file_path, 'w', encoding='utf-8') as f:
                    f.write(new_content)
            else:
                print(f"{RED}Invalid frontmatter format in {filename}{RESET}")
                return
        else:
            print(f"{RED}No frontmatter found in {filename}{RESET}")
            return
        
        # Move file to Rejected directory
        rejected_dir = Path(REJECTED_DIR)
        rejected_dir.mkdir(parents=True, exist_ok=True)
        
        new_file_path = rejected_dir / filename
        file_path.rename(new_file_path)
        
        print(f"{RED}❌ Rejected! File moved to Rejected folder{RESET}")
        
    except Exception as e:
        print(f"{RED}Error rejecting file {filename}: {str(e)}{RESET}")


def main():
    parser = argparse.ArgumentParser(description="Approval CLI Tool for Human Workflow")
    subparsers = parser.add_subparsers(dest='command', help='Available commands')
    
    # List command
    list_parser = subparsers.add_parser('list', help='List all pending approvals')
    
    # Show command
    show_parser = subparsers.add_parser('show', help='Show full content of approval request')
    show_parser.add_argument('filename', help='Name of the approval file to show')
    
    # Approve command
    approve_parser = subparsers.add_parser('approve', help='Approve an approval request')
    approve_parser.add_argument('filename', help='Name of the approval file to approve')
    
    # Reject command
    reject_parser = subparsers.add_parser('reject', help='Reject an approval request')
    reject_parser.add_argument('filename', help='Name of the approval file to reject')
    
    args = parser.parse_args()
    
    if args.command == 'list':
        list_approvals()
    elif args.command == 'show':
        show_approval(args.filename)
    elif args.command == 'approve':
        approve_file(args.filename)
    elif args.command == 'reject':
        reject_file(args.filename)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()