#!/usr/bin/env node
/**
 * Odoo MCP Server — Personal AI Employee (Gold Tier)
 *
 * Integrates with Odoo Community Edition via JSON-RPC API (Odoo 19+).
 * Reference: https://www.odoo.com/documentation/19.0/developer/reference/external_api.html
 *
 * All write operations (create invoice, record payment) require human approval
 * by default — draft-only mode unless force_execute=true is passed.
 *
 * Tools:
 *   - get_financial_summary    Weekly/monthly P&L summary for CEO Briefing
 *   - list_customers           List customers from Odoo CRM
 *   - create_customer          Create a new customer record
 *   - list_invoices            List invoices (with optional filter)
 *   - create_invoice_draft     Create a draft invoice (requires approval to post)
 *   - get_overdue_invoices     Get overdue unpaid invoices
 *   - get_account_balance      Get current account balances
 *   - search_products          Search product catalog
 *
 * Setup (.env):
 *   ODOO_URL=http://localhost:8069
 *   ODOO_DB=mycompany
 *   ODOO_USERNAME=admin
 *   ODOO_PASSWORD=admin
 */

import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";
import axios from "axios";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const VAULT_PATH = path.resolve(__dirname, "..", "..");
const PENDING_APPROVAL = path.join(VAULT_PATH, "Pending_Approval");

// ── Odoo JSON-RPC helpers ─────────────────────────────────────────────────────

function getOdooConfig() {
  const url = process.env.ODOO_URL || "http://localhost:8069";
  const db = process.env.ODOO_DB;
  const username = process.env.ODOO_USERNAME || "admin";
  const password = process.env.ODOO_PASSWORD;

  if (!db || !password) {
    throw new Error("ODOO_DB and ODOO_PASSWORD must be set in .env");
  }
  return { url, db, username, password };
}

let _uid = null;

async function odooAuthenticate() {
  if (_uid) return _uid;
  const cfg = getOdooConfig();

  const res = await axios.post(`${cfg.url}/web/dataset/call_kw`, {
    jsonrpc: "2.0",
    method: "call",
    params: {
      service: "common",
      method: "authenticate",
      args: [cfg.db, cfg.username, cfg.password, {}],
    },
  });

  if (!res.data.result) throw new Error("Odoo authentication failed. Check credentials.");
  _uid = res.data.result;
  return _uid;
}

async function odooCall(model, method, args = [], kwargs = {}) {
  const cfg = getOdooConfig();
  const uid = await odooAuthenticate();

  const res = await axios.post(`${cfg.url}/web/dataset/call_kw`, {
    jsonrpc: "2.0",
    method: "call",
    params: {
      model,
      method,
      args,
      kwargs: {
        ...kwargs,
        context: { lang: "en_US", tz: "UTC" },
      },
    },
  });

  if (res.data.error) throw new Error(JSON.stringify(res.data.error));
  return res.data.result;
}

async function odooSearchRead(model, domain = [], fields = [], limit = 50) {
  return odooCall(model, "search_read", [domain], { fields, limit });
}

function createApprovalFile(action, data) {
  fs.mkdirSync(PENDING_APPROVAL, { recursive: true });
  const ts = new Date().toISOString().replace(/[:.]/g, "-").slice(0, 19);
  const filename = `ODOO_${action.toUpperCase()}_${ts}.md`;
  const filepath = path.join(PENDING_APPROVAL, filename);

  const content = `---
type: odoo_action
action: ${action}
created: ${new Date().toISOString()}
status: pending_approval
approved: false
---

## Odoo Action Pending Approval

**Action:** ${action}

**Data:**
\`\`\`json
${JSON.stringify(data, null, 2)}
\`\`\`

---

## To Approve

Set \`approved: true\` in the frontmatter, OR move this file to \`Approved/\`.
The system will execute the Odoo action automatically after approval.

---
*Generated by Odoo MCP Server*
`;

  fs.writeFileSync(filepath, content, "utf8");
  return filename;
}

// ── MCP Server ────────────────────────────────────────────────────────────────

const server = new Server(
  { name: "odoo-mcp", version: "1.0.0" },
  { capabilities: { tools: {} } }
);

server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: [
    {
      name: "get_financial_summary",
      description:
        "Get a financial summary (revenue, expenses, outstanding invoices) for CEO Briefing. Read-only.",
      inputSchema: {
        type: "object",
        properties: {
          period: {
            type: "string",
            enum: ["this_week", "this_month", "this_quarter", "this_year"],
            description: "Reporting period (default: this_month)",
            default: "this_month",
          },
        },
      },
    },
    {
      name: "list_customers",
      description: "List customers from Odoo CRM. Read-only.",
      inputSchema: {
        type: "object",
        properties: {
          search: { type: "string", description: "Filter by name" },
          limit: { type: "number", default: 20 },
        },
      },
    },
    {
      name: "create_customer",
      description:
        "Create a new customer in Odoo. Creates approval request first (draft-only).",
      inputSchema: {
        type: "object",
        properties: {
          name: { type: "string", description: "Customer full name or company" },
          email: { type: "string" },
          phone: { type: "string" },
          is_company: { type: "boolean", default: false },
          force_execute: {
            type: "boolean",
            description: "Set true only if human already approved",
            default: false,
          },
        },
        required: ["name"],
      },
    },
    {
      name: "list_invoices",
      description: "List invoices from Odoo. Read-only.",
      inputSchema: {
        type: "object",
        properties: {
          state: {
            type: "string",
            enum: ["draft", "posted", "cancel", "all"],
            default: "all",
          },
          customer_name: { type: "string" },
          limit: { type: "number", default: 20 },
        },
      },
    },
    {
      name: "create_invoice_draft",
      description:
        "Create a DRAFT invoice in Odoo (does not post/finalize). Creates approval request in Pending_Approval/.",
      inputSchema: {
        type: "object",
        properties: {
          customer_name: { type: "string", description: "Customer name (must exist in Odoo)" },
          amount: { type: "number", description: "Invoice total amount" },
          description: { type: "string", description: "Invoice line description" },
          due_date: { type: "string", description: "Due date (YYYY-MM-DD)" },
          force_execute: {
            type: "boolean",
            description: "Set true only if human already approved",
            default: false,
          },
        },
        required: ["customer_name", "amount", "description"],
      },
    },
    {
      name: "get_overdue_invoices",
      description:
        "Get list of overdue unpaid invoices for CEO Briefing. Read-only.",
      inputSchema: { type: "object", properties: {} },
    },
    {
      name: "get_account_balance",
      description: "Get current account balances from Odoo chart of accounts. Read-only.",
      inputSchema: { type: "object", properties: {} },
    },
    {
      name: "search_products",
      description: "Search product catalog in Odoo. Read-only.",
      inputSchema: {
        type: "object",
        properties: {
          query: { type: "string" },
          limit: { type: "number", default: 20 },
        },
      },
    },
  ],
}));

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;

  try {
    if (name === "get_financial_summary") {
      const today = new Date();
      let dateFrom;
      const period = args.period || "this_month";

      if (period === "this_week") {
        dateFrom = new Date(today);
        dateFrom.setDate(today.getDate() - today.getDay());
      } else if (period === "this_month") {
        dateFrom = new Date(today.getFullYear(), today.getMonth(), 1);
      } else if (period === "this_quarter") {
        const q = Math.floor(today.getMonth() / 3);
        dateFrom = new Date(today.getFullYear(), q * 3, 1);
      } else {
        dateFrom = new Date(today.getFullYear(), 0, 1);
      }

      const dateFromStr = dateFrom.toISOString().split("T")[0];
      const dateToStr = today.toISOString().split("T")[0];

      const invoices = await odooSearchRead(
        "account.move",
        [
          ["move_type", "=", "out_invoice"],
          ["invoice_date", ">=", dateFromStr],
          ["invoice_date", "<=", dateToStr],
        ],
        ["name", "amount_total", "amount_residual", "payment_state", "invoice_date"],
        200
      );

      const totalRevenue = invoices.reduce((s, i) => s + (i.amount_total || 0), 0);
      const outstanding = invoices
        .filter((i) => i.payment_state !== "paid")
        .reduce((s, i) => s + (i.amount_residual || 0), 0);
      const paid = invoices.filter((i) => i.payment_state === "paid").length;

      return {
        content: [
          {
            type: "text",
            text: JSON.stringify({
              period,
              date_from: dateFromStr,
              date_to: dateToStr,
              total_invoiced: totalRevenue.toFixed(2),
              outstanding_receivable: outstanding.toFixed(2),
              invoices_count: invoices.length,
              paid_invoices: paid,
              unpaid_invoices: invoices.length - paid,
            }),
          },
        ],
      };
    }

    if (name === "list_customers") {
      const domain = args.search
        ? [["name", "ilike", args.search], ["customer_rank", ">", 0]]
        : [["customer_rank", ">", 0]];
      const customers = await odooSearchRead(
        "res.partner",
        domain,
        ["id", "name", "email", "phone", "is_company"],
        args.limit || 20
      );
      return {
        content: [{ type: "text", text: JSON.stringify({ customers, count: customers.length }) }],
      };
    }

    if (name === "create_customer") {
      if (!args.force_execute) {
        const filename = createApprovalFile("create_customer", args);
        return {
          content: [
            {
              type: "text",
              text: JSON.stringify({
                approval_required: true,
                approval_file: filename,
                message: "Customer creation queued for approval in Pending_Approval/",
              }),
            },
          ],
        };
      }

      const customerId = await odooCall("res.partner", "create", [
        {
          name: args.name,
          email: args.email || false,
          phone: args.phone || false,
          is_company: args.is_company || false,
          customer_rank: 1,
        },
      ]);
      return {
        content: [
          { type: "text", text: JSON.stringify({ success: true, customer_id: customerId, name: args.name }) },
        ],
      };
    }

    if (name === "list_invoices") {
      const domain = [];
      if (args.state && args.state !== "all") domain.push(["state", "=", args.state]);
      if (args.customer_name)
        domain.push(["partner_id.name", "ilike", args.customer_name]);
      domain.push(["move_type", "=", "out_invoice"]);

      const invoices = await odooSearchRead(
        "account.move",
        domain,
        ["id", "name", "partner_id", "amount_total", "amount_residual", "state", "payment_state", "invoice_date", "invoice_date_due"],
        args.limit || 20
      );
      return {
        content: [{ type: "text", text: JSON.stringify({ invoices, count: invoices.length }) }],
      };
    }

    if (name === "create_invoice_draft") {
      if (!args.force_execute) {
        const filename = createApprovalFile("create_invoice", args);
        return {
          content: [
            {
              type: "text",
              text: JSON.stringify({
                approval_required: true,
                approval_file: filename,
                message: "Invoice creation queued for approval in Pending_Approval/",
              }),
            },
          ],
        };
      }

      // Find customer
      const partners = await odooSearchRead(
        "res.partner",
        [["name", "ilike", args.customer_name]],
        ["id", "name"],
        1
      );
      if (!partners.length) throw new Error(`Customer not found: ${args.customer_name}`);

      const invoiceId = await odooCall("account.move", "create", [
        {
          move_type: "out_invoice",
          partner_id: partners[0].id,
          invoice_date: new Date().toISOString().split("T")[0],
          invoice_date_due: args.due_date || false,
          invoice_line_ids: [
            [
              0,
              0,
              {
                name: args.description,
                quantity: 1,
                price_unit: args.amount,
              },
            ],
          ],
        },
      ]);

      return {
        content: [
          {
            type: "text",
            text: JSON.stringify({
              success: true,
              invoice_id: invoiceId,
              message: `Draft invoice created for ${args.customer_name} — $${args.amount}. Not yet posted.`,
            }),
          },
        ],
      };
    }

    if (name === "get_overdue_invoices") {
      const today = new Date().toISOString().split("T")[0];
      const invoices = await odooSearchRead(
        "account.move",
        [
          ["move_type", "=", "out_invoice"],
          ["payment_state", "!=", "paid"],
          ["invoice_date_due", "<", today],
          ["state", "=", "posted"],
        ],
        ["id", "name", "partner_id", "amount_residual", "invoice_date_due"],
        50
      );
      const total = invoices.reduce((s, i) => s + (i.amount_residual || 0), 0);
      return {
        content: [
          {
            type: "text",
            text: JSON.stringify({
              overdue_invoices: invoices,
              count: invoices.length,
              total_overdue: total.toFixed(2),
            }),
          },
        ],
      };
    }

    if (name === "get_account_balance") {
      const accounts = await odooSearchRead(
        "account.account",
        [["deprecated", "=", false]],
        ["id", "code", "name", "account_type"],
        100
      );
      return {
        content: [{ type: "text", text: JSON.stringify({ accounts, count: accounts.length }) }],
      };
    }

    if (name === "search_products") {
      const domain = args.query ? [["name", "ilike", args.query]] : [];
      const products = await odooSearchRead(
        "product.product",
        domain,
        ["id", "name", "list_price", "categ_id"],
        args.limit || 20
      );
      return {
        content: [{ type: "text", text: JSON.stringify({ products, count: products.length }) }],
      };
    }

    throw new Error(`Unknown tool: ${name}`);
  } catch (error) {
    const msg = error.response?.data
      ? JSON.stringify(error.response.data)
      : error.message;
    return {
      content: [{ type: "text", text: JSON.stringify({ error: msg }) }],
      isError: true,
    };
  }
});

const transport = new StdioServerTransport();
await server.connect(transport);
